import React from 'react';
import Header from "@/features/header";
import BackSquare from '@/features/ui/square';
import {Train_One} from "next/font/google"

const TrainOneFont = Train_One({
    weight: "400",
    subsets: ["latin"],
  });;

export default function Introduction() {
    return(
        <>
            <Header></Header>
            <div className='main justify-center flex flex-wrap pt-[70px] pb-[40px] bg-kct-black'>
                <h1 className={`${TrainOneFont.className} year text-4xl w-full p-[2%] text-white`}>1年生</h1>
                <BackSquare
                    BGColor="border-sky-600"
                    Class="1-1"
                    Title="脱獄タイムアタック"
                    Intro="刑務所からの脱獄！罠や謎を速く正確に解きまくれ！！"

                />
                <BackSquare
                    BGColor='border-white'
                    Class="1-2"
                    Title="ホラー脱出ゲーム"
                    Intro="私たちはホラー要素を含んだ脱出ゲームを作りました。是非いらしてください。"
                />
                <BackSquare
                    BGColor='border-green-600'
                    Class="1-3"
                    Title="亡くし者"
                    Intro="カラダ探しをモチーフにお化け屋敷を作りました！"
                />
                <BackSquare
                    BGColor='border-kct-yellow'
                    Class="1-4"
                    Title="高専カジノ"
                    Intro="遊びながら『景品』で大儲けも夢じゃない！？(子供も遊べます)"
                />
                <BackSquare
                    BGColor='border-red-600'
                    Class="1-5"
                    Title="メカニカルシューター"
                    Intro="あなたの家に特殊部隊が攻め込んできても安心安全撃退できます！"
                />
                <h1 className={`${TrainOneFont.className} year text-4xl w-full p-[2%] text-white`}>2年生</h1>
                <BackSquare
                    BGColor="border-sky-600"
                    Class="2-1"
                    Title="バルーンアート教室"
                    Intro="2-1生徒と一緒にバルーンアートを作ったり，作ったアートを展示します"
                />
                <BackSquare
                    BGColor='border-white'
                    Class="2-2"
                    Title="カジノ"
                    Intro="2-2 様々なカジノゲームで遊びます"
                />
                <BackSquare
                    BGColor='border-green-600'
                    Class="2-3"
                    Title="フォトスポット"
                    Intro="<ここにキャッチコピーを入力してください>"
                />
                <BackSquare
                    BGColor='border-kct-yellow'
                    Class="2-4"
                    Title="VS2-4"
                    Intro="VS嵐を基に3つの遊びを用意しています！ぜひ遊びに来てください！"
                />
                <BackSquare
                    BGColor='border-red-600'
                    Class="2-5"
                    Title="お化け屋敷"
                    Intro="暗闇の中にこわ～いお化けが潜んでいるかも？！ぜひお越しください！"
                />
                <h1 className={`${TrainOneFont.className} year text-4xl w-full p-[2%] text-white`}>3年生</h1>
                <BackSquare
                    BGColor="border-sky-600"
                    Class="3-1"
                    Title="キッキングスナイパー"
                    Intro="某テレビ番組で大人気だったゲームが復活！思い切り楽しもう！"
                />
                <BackSquare
                    BGColor='border-white'
                    Class="3-2"
                    Title="脱出ゲーム"
                    Intro="ピクミンをモチーフにした脱出ゲームです。ぜひ来てください"
                />
                <BackSquare
                    BGColor='border-green-600'
                    Class="3-3"
                    Title="ハリーポッターと3Eの部屋"
                    Intro="人気映画ハリー・ポッターの舞台が高専に！？君達も魔法を体験してみよう！！写真も撮れるよ！！"
                />
                <BackSquare
                    BGColor='border-kct-yellow'
                    Class="3-4"
                    Title="コウセンオー＆類似マンション"
                    Intro="デジタルカードゲーム＆ルイ〇ジマンションに類似したマンション"
                />
                <BackSquare
                    BGColor='border-red-600'
                    Class="3-5"
                    Title="高専人生ゲーム"
                    Intro="高専生をゲームで類似した"
                />
                <h1 className={`${TrainOneFont.className} year text-4xl w-full p-[2%] text-white`}>4年生</h1>
                <BackSquare
                    BGColor="border-sky-600"
                    Class="4-M(機械)"
                    Title="KOUSEN UCHIDA"
                    Intro="フォトスポットです(*^^*)ぜひみんな来てください"
                />
                <BackSquare
                    BGColor='border-white'
                    Class="4-R(知能)"
                    Title="ピタゴラレース"
                    Intro="ピタゴラスイ〇チ風のビー玉レースを予定しています"
                />
                <BackSquare
                    BGColor='border-green-600'
                    Class="4-E(電気)"
                    Title="人間モグラ叩き"
                    Intro="説明"
                />
                <BackSquare
                    BGColor='border-kct-yellow'
                    Class="4-I(情報)"
                    Title="4Iプロコン"
                    Intro="詳しくはこのQRコードをチェック！"
                />
                <BackSquare
                    BGColor='border-red-600'
                    Class="4-C(科学)"
                    Title="科学遊び"
                    Intro="皆が知っているあの遊びに科学風にアレンジしました！"
                />
                <h1 className={`${TrainOneFont.className} year text-4xl w-full p-[2%] text-white`}>5年生</h1>
                <BackSquare
                    BGColor="border-sky-600"
                    Class="5-M(機械)"
                    Title="ロボット展示"
                    Intro="授業で作ったロボットを展示しています！ぜひ来てください！"
                />
                <BackSquare
                    BGColor='border-white'
                    Class="5-R(知能)"
                    Title="人間サイズボードゲーム"
                    Intro="ハリー・ポッターの世界を再現！等身大のチェス駒を動かして楽しもう"
                />
                <BackSquare
                    BGColor='border-green-600'
                    Class="5-E(電気)"
                    Title="手作り射的"
                    Intro="手作り射的で動く的を射抜くゲームです。目指せハイスコア！"
                />
                <BackSquare
                    BGColor='border-kct-yellow'
                    Class="5-I(情報)"
                    Title="nit-kit-center"
                    Intro="高専で学んだ魏喩つの集大成！手作りゲームセンターで特別な体験を！"
                />
                <BackSquare
                    BGColor='border-red-600'
                    Class="5-C(科学)"
                    Title="劇場版名探偵みっちゃん~手殷の前夜祭~"
                    Intro="5Cにて殺人事件！？見た目は少年頭脳は中年その名も名探偵みっちゃん"
                />
                <h1 className={`${TrainOneFont.className} year text-4xl w-full p-[2%] text-white`}>クラブバザー</h1>
                <h3 className={`${TrainOneFont.className} year text-3xl w-full p-[2%] text-white`}>屋内バザー</h3>
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="コンピュータ研究会"
                    Intro="オリジナルグッズ"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="美術部"
                    Intro="イラスト本，色紙，ポスターカード"
                />
                <h2 className={`${TrainOneFont.className} year text-3xl w-full p-[2%] text-white`}>屋外バザー</h2>
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="弓道部"
                    Intro="焼き鳥"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="吹奏楽部"
                    Intro="フランクフルト"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="卓球部"
                    Intro="わらび餅ドリンク"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="バドミントン部"
                    Intro="五平餅"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="科学愛好会"
                    Intro="白玉団子"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="高専企業部"
                    Intro="キーホルダー"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="ロボットデザイン研究会"
                    Intro="ベビーカステラ"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="硬式テニス部"
                    Intro="フルーツドリンク"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="武道部(空手，柔道，剣道）"
                    Intro="白玉ソーダ"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="女子寮"
                    Intro="ワッフル"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="陸上部"
                    Intro="カレー"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="ソフトテニス部"
                    Intro="わたがし"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="女子バスケ部"
                    Intro="焼きうどん"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="ラグビー部"
                    Intro="プロテイン飲料"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="サッカー部"
                    Intro="うどん"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="男子バスケ部"
                    Intro="ホットサンド"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="男子寮"
                    Intro="焼き餃子"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="野球部"
                    Intro="ホットドッグ"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="男子バレー部"
                    Intro="たこ焼き"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="ハンドボール部"
                    Intro="焼きそば"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="ロボコン"
                    Intro="パンケーキ"
                />
                <BackSquare
                    BGColor='border-sky-300'
                    Club={true}
                    Title="学生会"
                    Intro="フライドポテト・ベビーカステラ"
                />
            </div>
        </>
    );
}